import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from 'docx';
import type { ChatMessage } from '@docintel/ai-engine';

export async function exportChatToDocx(
  messages: ChatMessage[],
  title: string,
): Promise<Blob> {
  const children: Paragraph[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by DocIntel on ${new Date().toLocaleDateString()}`,
          italics: true,
          color: '888888',
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  ];

  for (const msg of messages) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: msg.role === 'user' ? 'You: ' : 'DocIntel: ',
            bold: true,
          }),
        ],
        spacing: { before: 200 },
      }),
      new Paragraph({
        children: [new TextRun({ text: msg.content })],
        spacing: { after: 200 },
      }),
    );
  }

  const doc = new Document({
    sections: [{ children }],
  });

  return Packer.toBlob(doc);
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
