import { jsPDF } from 'jspdf';
import type { ChatMessage } from '@docintel/ai-engine';

export function exportChatToPdf(messages: ChatMessage[], title: string): Blob {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  doc.setFontSize(18);
  doc.text(title, pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(136, 136, 136);
  doc.text(`Generated by DocIntel on ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: 'center' });
  y += 15;

  doc.setTextColor(0, 0, 0);

  for (const msg of messages) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    const roleLabel = msg.role === 'user' ? 'You' : 'DocIntel';
    doc.text(`${roleLabel}:`, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(msg.content, maxWidth);
    for (const line of lines) {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += 5;
    }
    y += 8;
  }

  return doc.output('blob');
}
